services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app/backend
      - /app/backend/node_modules
      - ./backend/logs:/app/backend/logs
    environment:
      - NODE_ENV=${NODE_ENV}
      - MONGO_URL=${MONGO_URL}
      - HOST=${HOST}
      - PORT=${PORT}
      - API_VERSION=${API_VERSION}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongodb
  
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
    command: ["--replSet", "rs0"]

  mongors-init:
    image: mongo:latest
    depends_on:
      - mongodb
    entrypoint: >
      bash -c "
        sleep 5;
        mongosh --host mongodb --eval '
          try {
            rs.initiate({ _id: \"rs0\", members: [{ _id: 0, host: \"mongodb:27017\" }] })
          } catch(e) {
            print(e.message)
          }'
      "
    restart: "no"

volumes:
  mongodb_data: