version: "3.9"

services:
  backend:
    image: mydockerhubuser/webdoluuniem_backend:latest
    ports:
      - "8000:3001"
    volumes:
      - backend_logs:/app/backend/logs
    environment:
      NODE_ENV: "production"
      MONGO_URL: "mongodb://mongodb:27017/mydb"
      HOST: "0.0.0.0"
      PORT: "3001"
      API_VERSION: "v1"
      MEILISEARCH_HOST: "http://meilisearch:7700"
    secrets:
      - jwt_secret
      - sendgrid_api_key
      - sendgrid_from_email
      - partner_code
      - access_key
      - secret_key
      - endpoint
      - return_url
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  frontend:
    image: mydockerhubuser/webdoluuniem_frontend:latest
    ports:
      - "3000:80"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  mongodb:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
    command: ["--replSet", "rs0"]
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  mongors-init:
    image: mongo:latest
    depends_on:
      - mongodb
    entrypoint: >
      bash -c "
        sleep 5;
        mongosh --host mongodb --eval '
          try {
            rs.initiate({ _id: \"rs0\", members: [{ _id: 0, host: \"mongodb:27017\" }] })
          } catch(e) {
            print(e.message)
          }'
      "
    deploy:
      restart_policy:
        condition: none

  meilisearch:
    image: getmeili/meilisearch:latest
    ports:
      - "7701:7700"
    volumes:
      - meili_data:/meili_data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

volumes:
  backend_logs:
  mongodb_data:
  meili_data:

secrets:
  jwt_secret:
    external: true
  sendgrid_api_key:
    external: true
  sendgrid_from_email:
    external: true
  partner_code:
    external: true
  access_key:
    external: true
  secret_key:
    external: true
  endpoint:
    external: true
  return_url:
    extern
